### ISSUE TITLE
Add eslint-plugin-jsdoc

### ISSUE THREAD

**Issue by SammyBaek** [SyncM8/syncm8#18]
Had this in, but `pre-commit` github action did not like it: https://github.com/SyncM8/syncm8/runs/3594842773

```
Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Object.values(...).flat is not a function
Occurred while linting /home/runner/work/syncm8/syncm8/client/src/App.tsx:12
    at Object.isValidTag (/home/runner/work/syncm8/syncm8/client/node_modules/eslint-plugin-jsdoc/dist/jsdocUtils.js:344:78)
    at Object.utils.isValidTag (/home/runner/work/syncm8/syncm8/client/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:458:32)
    at jsdoc.tags.forEach.jsdocTag (/home/runner/work/syncm8/syncm8/client/node_modules/eslint-plugin-jsdoc/dist/rules/checkTagNames.js:66:15)
    at Array.forEach (<anonymous>)
    at _default (/home/runner/work/syncm8/syncm8/client/node_modules/eslint-plugin-jsdoc/dist/rules/checkTagNames.js:59:14)
    at iterate (/home/runner/work/syncm8/syncm8/client/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:784:3)
    at jsdocNodes.forEach.jsdocNode (/home/runner/work/syncm8/syncm8/client/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:866:7)
    at Array.forEach (<anonymous>)
    at callIterator (/home/runner/work/syncm8/syncm8/client/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:829:16)
    at *:not(Program) (/home/runner/work/syncm8/syncm8/client/node_modules/eslint-plugin-jsdoc/dist/iterateJsdoc.js:925:11)

Error: The process '/opt/hostedtoolcache/Python/3.8.11/x64/bin/pre-commit' failed with exit code 1
```

**Comment by EpicPi** [comment]
docker?
